version: '3'
services:
  web:
    build: .
    environment:
      - DATABASE_USR=root
      - DATABASE_PWD=password17e3
      - DATABASE_HOST=postgres
      - DATABASE_NAME=eleven_bot
      - APP_ENV=development
    command: |
      ./bin/wait-for-it.sh postgres:5432 -- bash -c "bundle exec rake db:migrate && bundle exec rackup -p 80"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./:/app
    ports:
      - "4000:80"

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password17e3
      - POSTGRES_DB=eleven_bot
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432"
